SBMMember.Web/Models/MemberListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SBMMember.Models.MemberSearch;
namespace SBMMember.Web.Models
{
    public class MemberListViewModel
    {
        public List<MemberSearchByDTO> memberList { get; set; }
    }
}

SBMMember.Web/Controllers/ManageMembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SBMMember.Data.DataFactory;
using SBMMember.Web.Models;
using SBMMember.Models;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using SBMMember.Web.Helper;
using NToastNotify;
using System.IO;
using Microsoft.AspNetCore.Hosting;
namespace SBMMember.Web.Controllers
{
    // [Authorize]
    public class ManageMembersController : Controller
    {
        private readonly IMemberDataFactory memberDataFactory;
        private readonly IMemberSearchDataFactory memberSearchDataFactory;

        private readonly IMemberPersonalDataFactory personalDataFactory;
        private readonly IMemberContactDetailsDataFactory contactDetailsDataFactory;
        private readonly IMemberEducationEmploymentDataFactory educationEmploymentDataFactory;
        private readonly IMemberFamilyDetailsDataFactory familyDetailsDataFactory;
        private readonly IMemberPaymentsDataFactory paymentsDataFactory;
        private readonly IMapper mapper;
        private readonly IMemberFormStatusDataFactory formStatusDataFactory;
        private readonly IEventTitlesDataFactory eventTitlesDataFactory;
        private readonly IToastNotification _toastNotification;
        private readonly IWebHostEnvironment Environment;

        public ManageMembersController(IMemberDataFactory dataFactory,
            IMemberSearchDataFactory searchDataFactory,
            IMemberPersonalDataFactory _personalDataFactory,
            IMemberContactDetailsDataFactory _contactDetailsDataFactory,
            IMemberEducationEmploymentDataFactory _educationEmploymentDataFactory,
            IMemberFamilyDetailsDataFactory _familyDetailsDataFactory,
            IMemberPaymentsDataFactory _paymentsDataFactory,
            IMapper _mapper,
            IMemberFormStatusDataFactory _formStatusDataFactory,
            IEventTitlesDataFactory _eventTitlesDataFactory,
            IToastNotification toast,
            IWebHostEnvironment environment
            )
        {
            memberDataFactory = dataFactory;
            memberSearchDataFactory = searchDataFactory;
            personalDataFactory = _personalDataFactory;
            contactDetailsDataFactory = _contactDetailsDataFactory;
            educationEmploymentDataFactory = _educationEmploymentDataFactory;
            familyDetailsDataFactory = _familyDetailsDataFactory;
            paymentsDataFactory = _paymentsDataFactory;
            mapper = _mapper;
            formStatusDataFactory = _formStatusDataFactory;
            eventTitlesDataFactory = _eventTitlesDataFactory;
            _toastNotification = toast;
            Environment = environment;
        }
        public IActionResult MemberList()
        {
            MemberListViewModel model = new MemberListViewModel()
            {
                memberList = memberSearchDataFactory.GetAllApprovedMembers()
            };
            return View(model);
        }
        public IActionResult NewMemberList()
        {
            MemberListViewModel model = new MemberListViewModel()
            {
                memberList = memberSearchDataFactory.GetAllNewlySubmittedMembers()
            };
            return View(model);
        }
        public IActionResult VerifyMemberProfile(int MemberId)
        {
            MemberFormCommonViewModel commonViewModel = new MemberFormCommonViewModel();

            //var memberId = User.Claims?.FirstOrDefault(x => x.Type.Equals("MemberId", StringComparison.OrdinalIgnoreCase))?.Value;
            int _MemberId = MemberId;
            commonViewModel.MemberId = MemberId;
            Member_PersonalDetails member_Personal = personalDataFactory.GetMemberPersonalDetailsByMemberId(_MemberId);
            MemberPerosnalInfoViewModel perosnalInfoViewModel = mapper.Map<MemberPerosnalInfoViewModel>(member_Personal);
            commonViewModel.MemberPersonalInfo = perosnalInfoViewModel;

            Member_ContactDetails member_contact = contactDetailsDataFactory.GetDetailsByMemberId(_MemberId);
            MemberContactInfoViewModel contactInfoViewModel = mapper.Map<MemberContactInfoViewModel>(member_contact);
            commonViewModel.MemberConatctInfo = contactInfoViewModel;

            Member_EducationEmploymentDetails member_education = educationEmploymentDataFactory.GetDetailsByMemberId(_MemberId);
            MemberEducationEmploymentInfoViewModel educationEmploymentInfoViewModel = mapper.Map<MemberEducationEmploymentInfoViewModel>(member_education);
            commonViewModel.MemberEducationEmploymentInfo = educationEmploymentInfoViewModel;

            List<Member_FamilyDetails> member_Family = familyDetailsDataFactory.GetFamilyDetailsByMemberId(_MemberId);
            List<MemberFamilyInfoViewModel> memberFamilies = new List<MemberFamilyInfoViewModel>();
            foreach (Member_FamilyDetails family in member_Family)
            {
                memberFamilies.Add(mapper.Map<MemberFamilyInfoViewModel>(family));
            }
            MemberFamilyInfoViewModel familyInfoViewModel = new MemberFamilyInfoViewModel();
            familyInfoViewModel.MemberFamilyDetails = memberFamilies;
            //familyInfoViewModel.DOB = DateTime.Now.AddYears(-72);
            commonViewModel.MemberFamilyInfo = familyInfoViewModel;

            Member_PaymentsAndReciepts member_Payments = paymentsDataFactory.GetDetailsByMemberId(_MemberId);
            MemberPaymentRecieptsViewModel paymentViewModel = mapper.Map<MemberPaymentRecieptsViewModel>(member_Payments);
            paymentViewModel.LastMemberShipId = paymentsDataFactory.LastMembershipNo();
            commonViewModel.MemberPaymentInfo = paymentViewModel;

            if (TempData.ContainsKey("PersonalTabActive"))
            {
                commonViewModel.MemberPersonalInfo.ActiveTab = "Checked";
                TempData.Remove("PersonalTabActive");
            }
            else if (TempData.ContainsKey("ContactTabActive"))
            {
                commonViewModel.MemberConatctInfo.ActiveTab = "Checked";
                TempData.Remove("ContactTabActive");
            }
            else if (TempData.ContainsKey("EduEmpTabActive"))
            {
                commonViewModel.MemberEducationEmploymentInfo.ActiveTab = "Checked";
                TempData.Remove("EduEmpTabActive");
            }
            else if (TempData.ContainsKey("FamilyTabActive"))
            {
                commonViewModel.MemberFamilyInfo.ActiveTab = "Checked";
                TempData.Remove("FamilyTabActive");
            }
            else if(TempData.ContainsKey("PaymentTabActive"))
            {
                commonViewModel.MemberPaymentInfo.ActiveTab = "Checked";
                TempData.Remove("PaymentTabActive");
            }
            else
            {
                commonViewModel.MemberPersonalInfo.ActiveTab = "Checked";
            }

            return View(commonViewModel);
            //return  RedirectToAction("NewMemberList");
        }
        public IActionResult VerifyMemberProfileNew(MemberFamilyInfoViewModel familymodel)
        {
            MemberFormCommonViewModel commonViewModel = new MemberFormCommonViewModel();

            //var memberId = User.Claims?.FirstOrDefault(x => x.Type.Equals("MemberId", StringComparison.OrdinalIgnoreCase))?.Value;
            int _MemberId = familymodel.MemberId;

            Member_PersonalDetails member_Personal = personalDataFactory.GetMemberPersonalDetailsByMemberId(_MemberId);
            MemberPerosnalInfoViewModel perosnalInfoViewModel = mapper.Map<MemberPerosnalInfoViewModel>(member_Personal);
            commonViewModel.MemberPersonalInfo = perosnalInfoViewModel;

            Member_ContactDetails member_contact = contactDetailsDataFactory.GetDetailsByMemberId(_MemberId);
            MemberContactInfoViewModel contactInfoViewModel = mapper.Map<MemberContactInfoViewModel>(member_contact);
            commonViewModel.MemberConatctInfo = contactInfoViewModel;

            Member_EducationEmploymentDetails member_education = educationEmploymentDataFactory.GetDetailsByMemberId(_MemberId);
            MemberEducationEmploymentInfoViewModel educationEmploymentInfoViewModel = mapper.Map<MemberEducationEmploymentInfoViewModel>(member_education);
            commonViewModel.MemberEducationEmploymentInfo = educationEmploymentInfoViewModel;

            List<Member_FamilyDetails> member_Family = familyDetailsDataFactory.GetFamilyDetailsByMemberId(_MemberId);
            List<MemberFamilyInfoViewModel> memberFamilies = new List<MemberFamilyInfoViewModel>();
            foreach (Member_FamilyDetails family in member_Family)
            {
                memberFamilies.Add(mapper.Map<MemberFamilyInfoViewModel>(family));
            }
            //MemberFamilyInfoViewModel familyInfoViewModel = new MemberFamilyInfoViewModel();
            //familyInfoViewModel.MemberFamilyDetails = memberFamilies;
            //commonViewModel.MemberFamilyInfo = familyInfoViewModel;
            familymodel.MemberFamilyDetails = memberFamilies;
            familymodel.IsNew = false;
            commonViewModel.MemberFamilyInfo = familymodel;
            Member_PaymentsAndReciepts member_Payments = paymentsDataFactory.GetDetailsByMemberId(_MemberId);
            MemberPaymentRecieptsViewModel paymentViewModel = mapper.Map<MemberPaymentRecieptsViewModel>(member_Payments);
            paymentViewModel.LastMemberShipId = paymentsDataFactory.LastMembershipNo();
            commonViewModel.MemberPaymentInfo = paymentViewModel;


            if (TempData.ContainsKey("PersonalTabActive"))
            {
                commonViewModel.MemberPersonalInfo.ActiveTab = "Checked";
                TempData.Remove("PersonalTabActive");
            }
            else if (TempData.ContainsKey("ContactTabActive"))
            {
                commonViewModel.MemberConatctInfo.ActiveTab = "Checked";

SBMMember.Web/Views/ManageMembers/MemberList.cshtml
@model MemberListViewModel
@{
    ViewData["Title"] = "MemberList";
    Layout = "~/Views/Shared/_LayoutAdminDashboard.cshtml";
}


<script>
    $(document).ready(function () {
        $("#BusinessForm").hide();
        $('#tblJobPost').DataTable();
        $("#btnAddNew").click(function () {
            $("#BusinessForm").show();
            $(this).hide();
        });
        $("#btnCancel").click(function () {
            $("#BusinessForm").hide();
            $("#btnAddNew").show();
        });
    });
</script>

<section class="blog_area single-post-area section_padding">
    <div class="container">

        <div class="row">
            <div class="col-lg-12">
                <div class="scroll">
                    <p> Approved Member List</p>
                </div>
                <div>
                </div>
            </div>
        </div>




    </div>


    <div class="container">

        <div class="row">
            <div class="col-lg-12">
                <table id="tblJobPost" class="display" style="width:100%">
                    <thead>
                        <tr>
                            <th>Membership Id</th>
                            <th>Prefix</th>
                            <th>FirstName</th>
                            <th>MiddleName</th>
                            <th>LastName</th>
                            <th>Mobile</th>
                            <th>City</th>
                           <th>Form Status</th>
                            <th>Operations</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.memberList != null)
                        {
                            foreach (var member in Model.memberList)
                            {
                        <tr>
                            <td>@member.MemberShippId</td>
                            <td>@member.Prefix</td>
                            <td>@member.FirstName</td>
                            <td>@member.MiddleName</td>
                            <td>@member.LastName</td>
                            <td>@member.MobileNumber</td>
                            <td>@member.City</td>
                            <td>@member.FormStatus</td>
                            <td>
                                <a title="View Profile" href="@Url.Action("VerifyMemberProfile","ManageMembers",new { memberId = member.MemberId})"><i class="ti-search"></i> View Profile</a>
                                <a title="DeActivate" href="@Url.Action("DeActivateMemberProfile","ManageMembers",new { memberId = member.MemberId})"><i class="ti-control-pause"></i> DeActivate</a>
                            </td>
                        </tr>
                            }

                        }
                    </tbody>

                </table>
            </div>
        </div>
    </div>

</section>

SBMMember.Web/Views/ManageMembers/NewMemberList.cshtml
@model MemberListViewModel
@{
    ViewData["Title"] = "NewMemberList";
    Layout = "~/Views/Shared/_LayoutAdminDashboard.cshtml";
}

<script>
    $(document).ready(function () {
        $("#BusinessForm").hide();
        $('#tblJobPost').DataTable();
        $("#btnAddNew").click(function () {
            $("#BusinessForm").show();
            $(this).hide();
        });
        $("#btnCancel").click(function () {
            $("#BusinessForm").hide();
            $("#btnAddNew").show();
        });
    });
</script>

<section class="blog_area single-post-area section_padding">
    <div class="container">

        <div class="row">
            <div class="col-lg-12">
                <div class="scroll">
                    <p> New Member List</p>
                </div>
                <div>
                </div>
            </div>
        </div>



        
    </div>


    <div class="container">
        
        <div class="row">
            <div class="col-lg-12">
                <table id="tblJobPost" class="display" style="width:100%">
                    <thead>
                        <tr>
                            <th>Prefix</th>
                            <th>FirstName</th>
                            <th>MiddleName</th>
                            <th>LastName</th>
                            <th>Mobile</th>
                            <th>City</th>
                            <th>Form Status</th>
                            <th>Operations</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.memberList != null)
                        {
                            foreach (var member in Model.memberList)
                            {
                                <tr>
                                    <td>@member.Prefix</td>
                                    <td>@member.FirstName</td>
                                    <td>@member.MiddleName</td>
                                    <td>@member.LastName</td>
                                    <td>@member.MobileNumber</td>
                                    <td>@member.City</td>
                                    <td>@member.FormStatus</td>
                                    <td>
                                        <a title="Verfify" href="@Url.Action("VerifyMemberProfile","ManageMembers",new { memberId = member.MemberId})"><i class="ti-search"></i> Verify</a>
                                        @if (member.FormStatus == "Verified")
                                        {
                                        <a title="Approve" href="@Url.Action("ApproveMemberProfile", "ManageMembers", new { memberId = member.MemberId })" class="delete-row" onclick="return confirm('Are sure wants to Approve This Member Profile?');"><i class="ti-stamp"></i> Approve</a>
                                        }
                                    </td>
                                </tr>
                            }

                        }
                    </tbody>

                </table>
            </div>
        </div>
    </div>

</section>