SBMMember.Web/Models/MatrimonyViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SBMMember.Web.Models
{
    public class MatrimonyViewModel
    {
        public List<CandidateSearchResponse> Candidates { get; set; }
        public CandidateProfile CandidateProfile { get; set; }
    }
}

SBMMember.Web/Controllers/MatrimonyController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SBMMember.Web.Models;
using SBMMember.Web.Helper;
using Microsoft.AspNetCore.Authorization;
using SBMMember.Data.DataFactory;
namespace SBMMember.Web.Controllers
{
    [Authorize]
    public class MatrimonyController : Controller
    {
        private readonly IBannerAdsDataFactory bannerAdsDataFactory;
        public MatrimonyController(IBannerAdsDataFactory adsDataFactory)
        {
            bannerAdsDataFactory= adsDataFactory;

        }
        public IActionResult MatrimonySearch()
        {
            List<BannerClass> bannerClasses = bannerAdsDataFactory.GetBannerAds().Select(x => new BannerClass() { heading = x.Heading, imageURL = x.ImageURL }).ToList();
            BannerAndMarqueeViewModel viewModel = new BannerAndMarqueeViewModel()
            {
                //Banners = BannerHelper.GetBanners()
                Banners=bannerClasses
            };
            return View(viewModel);
        }
        public IActionResult VarSearch()
        {
            MatrimonyViewModel viewModel = new MatrimonyViewModel()
            {
                Candidates = Helper.MatrimonyHelper.GetAllVar()
            };
            return View("MatrimonyCandidateList",viewModel);
        }
        public IActionResult VadhuSearch()
        {
            MatrimonyViewModel viewModel = new MatrimonyViewModel()
            {
                Candidates = Helper.MatrimonyHelper.GetAllVadhus()
            };
            return View("MatrimonyCandidateList", viewModel);
        }

        public IActionResult MatrimonyCandidateProfile(string UserIdId)
        {
            MatrimonyViewModel viewModel = new MatrimonyViewModel()
            {
                CandidateProfile = Helper.MatrimonyHelper.GetCandidateProfileByCandidateId(UserIdId)
            };
            return View(viewModel);
        }
    }
}

SBMMember.Web/Views/Matrimony/MatrimonyCandidateList.cshtml
@model MatrimonyViewModel
@{
    ViewData["Title"] = "MatrimonyCandidateList";
    Layout = "~/Views/Shared/_LayoutMemberDashboard.cshtml";
}

@*<h1>Matrimony Candidate List</h1>*@
<div class="container-fluid" style="margin-top:30px">
    <div class="row">
        <div class="col-lg-12">
            <div class="scroll" style="background-color:darkred">
                <p> Welcome to Matrimony Portal</p>
            </div>
        </div>
    </div>
</div>
@if (Model.Candidates.Count > 0)
{
    foreach (CandidateSearchResponse candidate in Model.Candidates)
    {
        @await Html.PartialAsync("_PartialCandidateInfo", candidate)
    }
}

SBMMember.Web/Views/Matrimony/MatrimonyCandidateProfile.cshtml
@model MatrimonyViewModel
@{
    ViewData["Title"] = "MatrimonyCandidateProfile";
    Layout = "~/Views/Shared/_LayoutMemberDashboard.cshtml";
}
<div class="container-fluid" style="margin-top:30px">
    <div class="row">
        <div class="col-lg-12">
            <div class="scroll" style="background-color:darkred">
                <p> Welcome to Matrimony Portal</p>
            </div>
        </div>
    </div>
</div>
<section>

    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <table>
                <tr>
                <td style="background-color:#7c0053">
                    <div class="photo-container1">
                    <img src="@Model.CandidateProfile.profileImage" class="view_prof_i">
                    </div>
                </td>
                <td width="100%" style="background-color:#7c0053">
                            <section class="data-content1">
                                <table>
                                    <tr>
                                        <td><label class="lbl_profile"><strong>@Model.CandidateProfile.fullName</strong></label></td>
                                    </tr>
                                    <tr>
                                        <td><label class="lbl_profile"><strong>Age:@Model.CandidateProfile.age yrs </strong></label></td>
                                    </tr>
                                    <tr>
                                        <td><label class="lbl_profile"><strong>ऊंची: @Model.CandidateProfile.heightInFeet'@Model.CandidateProfile.heightInInches"</strong></label></td>
                                    </tr>
                                    <tr><td><label class="lbl_profile"><strong>Candidate Id: @Model.CandidateProfile.applicationId </strong></label></td></tr>
                                </table>        
                               </section>
                        </td>
                </tr>
                </table>
                <div class="col-rt-12">
                  
                    <div class="Scriptcontent">
                        <section class="tabs-container tab-text">
                            <label for="tab1" style="color:#ffffff;text-align:center"> <img src="~/img/profile.png" class="matri-icon"> <br>वैयक्तिक माहिती </label>
                            <label for="tab2" style="color:#ffffff;text-align:center"> <img src="~/img/mortarboard.png" class="matri-icon"><br> शिक्षण/नोकरी </label>
                            @*<label for="tab3" style="color:#ffffff;text-align:center"> <img src="~/img/image-gallery.png" class="matri-icon"><br>छायाचित्र</label>*@
                            <label for="tab4" style="color:#ffffff;text-align:center"> <img src="~/img/people.png" class="matri-icon"><br>कुटुंबाविषयी माहिती </label>
                            <label for="tab5" style="color:#ffffff;text-align:center"> <img src="~/img/contact-img.png" class="matri-icon"><br>संपर्कासाठी नाव</label>
                        </section>

                        <input name="tab" id="tab1" type="radio" checked />
                        <section class="tab-content">
                            
                            <div class="section-top-border">
                                <div class="row">
                                    <div class="col-lg-12 col-md-12" style="margin-left:10px; margin-top:10px">
                                        <h5><b>जन्म नाव:</b>  @Model.CandidateProfile.birthName</h5>
                                        <h5><b>जन्म ठिकाण:</b> @Model.CandidateProfile.birthPlace</h5>
                                        <h5><b>जन्म तारीख:</b> @Model.CandidateProfile.birthDate</h5>
                                        <h5><b>जन्म वेळ(24 hrs):</b> @Model.CandidateProfile.birthHrs:@Model.CandidateProfile.birthMins</h5>
                                        <h5><b>गोत्र:</b> @Model.CandidateProfile.gotra</h5>
                                        <h5><b>रक्तगट:</b> @Model.CandidateProfile.bloodGroup</h5>
                                        <h5><b>मामकुळ:</b> @Model.CandidateProfile.mamkul</h5>
                                        <h5><b>संपर्क नं:</b> @Model.CandidateProfile.mobileNo</h5>
                                    </div>
                                </div>
                            </div>
                        </section>

                        <input name="tab" id="tab2" type="radio" />
                        <section class="tab-content">
                          
                            <div class="section-top-border">
                                <div class="row">
                                    <div class="col-lg-12 col-md-12" style="margin-left:10px; margin-top:10px">
                                            <h5><b>शैक्षणिक पातळी:</b> @Model.CandidateProfile.educationLevel</h5>
                                            <h5><b>शिक्षण:</b> @Model.CandidateProfile.qualification</h5>
                                            <h5><b>नोकरी / व्यवसाय:</b> @Model.CandidateProfile.occupation</h5>
                                            <h5><b>जोडीदाराविषयी अपेक्षा:</b> @Model.CandidateProfile.expectations</h5>
                                    </div>
                                </div>
                            </div>
                        </section>

                        <input name="tab" id="tab3" type="radio" />
                        <section class="tab-content">
                            
                            <div class="section-top-border">
                                <div class="row">
                                    <div class="col-lg-12 col-md-12" style="margin-left:10px; margin-top:10px">
                                       
                                    </div>

                                </div>
                            </div>
                        </section>

                        <input name="tab" id="tab4" type="radio" />
                        <section class="tab-content">
                          
                            <div class="section-top-border">
                                <div class="row">
                                    <div class="col-lg-12 col-md-12" style="margin-left:10px; margin-top:10px">
                                            <h5><b>भाऊ विवाहित:</b> @Model.CandidateProfile.broMarried,अविवाहित @Model.CandidateProfile.broUnmarried</h5>
                                            <h5><b>बहीण विवाहित:</b> @Model.CandidateProfile.sisMarried,अविवाहित @Model.CandidateProfile.sisUnmarried</h5>
                                            <h5><b>मुळगाव:</b> @Model.CandidateProfile.homeTown</h5>
                                            <h5><b>तालुका:</b> @Model.CandidateProfile.taluka</h5>
                                            <h5><b>जिह्वा:</b> @Model.CandidateProfile.district</h5>
                                            <h5><b>वडीलांचे/पालकांचे नाव:</b> @Model.CandidateProfile.nameOfFatherGuardian</h5>
                                            <h5><b>पत्ता:</b> @Model.CandidateProfile.parentalAddress</h5>
                                            <h5><b>संपर्क नं:</b> @Model.CandidateProfile.parentalContactNo1</h5>
                                            <h5><b>इमेल:</b> @Model.CandidateProfile.parentalEmail</h5>
                                    </div>

                                </div>
                            </div>
                        </section>

                        <input name="tab" id="tab5" type="radio" />
                        <section class="tab-content">
                            
                            <div class="section-top-border">
                                <div class="row">
                                    <div class="col-lg-12 col-md-12" style="margin-left:10px; margin-top:10px">
                                      
                                            <h5><b>संपर्कांचे नाव १:</b> @Model.CandidateProfile.fatherGurdianTitle @Model.CandidateProfile.nameOfFatherGuardian</h5>
                                            <h5><b>पत्ता १:</b> @Model.CandidateProfile.parentalAddress</h5>
                                            <h5><b>संपर्क १:</b> @Model.CandidateProfile.parentalContactNo1</h5>
                                            <h5><b>संपर्कांचे नाव २:</b> @Model.CandidateProfile.altFatherGurdianTitle @Model.CandidateProfile.altNameOfFatherGuardian</h5>
                                            <h5><b>पत्ता २:</b> @Model.CandidateProfile.altParentalAddress</h5>
                                            <h5><b>संपर्क २:</b> @Model.CandidateProfile.altParentalContactNo1</h5>
                                    </div>

                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

SBMMember.Web/Views/Matrimony/MatrimonySearch.cshtml
@model BannerAndMarqueeViewModel
@{
    ViewData["Title"] = "MatrimonySearch";
    Layout = "~/Views/Shared/_LayoutMemberDashboard.cshtml";
}



<div class="container-fluid" style="margin-top:30px">
    <div class="row">
        <div class="col-lg-12">
            <div class="scroll" style="background-color:darkred">
                <p> Welcome to Matrimony Portal</p>
            </div>
        </div>
    </div>
</div>
<div class="seperate"></div>
<div class="container ">
    <div class="row">
        <div class="col-lg-12" style="text-align:center">
            <!------------icon dashbaord row-1--------------->
            <div class="container">
                <div class="row ">
                    <div class="col-xs-6 r1c1 dashboard" id="groom" style="cursor:pointer; margin-left:17%">
                        <a asp-action="VarSearch" asp-controller="Matrimony"> <img src="~/img/groom.png" class="dashboard-icon"></a>
                        <h3 style="color:#000000">वर</h3>
                    </div>
                    <div class="col-xs-6 r1c1 dashboard" id="bride" style="cursor:pointer">
                        <a asp-action="VadhuSearch" asp-controller="Matrimony">  <img src="~/img/bride.png" class="dashboard-icon"></a>
                        <h3 style="color:#000000">वधु</h3>
                    </div>
                </div>
            </div>
            <!------------End of icon dashbaord row-1--------------->
        </div>
    </div>
</div>
<div class="seperate"><hr style="border:1px dashed #a7a7a7"></div>
<div class="seperate"></div>
@await Html.PartialAsync("_PartialSlider")

<!--------------end of dashboard-------------->