SBMMember.Web/Models/SubscriptionViewModel.cs
using System.Collections.Generic;

namespace SBMMember.Web.Models
{
    public class SubscriptionViewModel
    {

        public int Id { get; set; }
        public int Charges { get; set; }

        public List<SubscriptionViewModel> SubCharges { get; set; }
    }
}

SBMMember.Web/Controllers/SubscriptionsController.cs
using Microsoft.AspNetCore.Mvc;
using SBMMember.Data.DataFactory;
using System.Collections.Generic;
using SBMMember.Models;
using SBMMember.Web.Models;
using System.Linq;
using NToastNotify;
namespace SBMMember.Web.Controllers
{
    public class SubscriptionsController : Controller
    {

        private readonly ISubscriptionDataFactory _subscriptionDataFactory;
        private readonly IMatrimonySubscriptionDataFactory matrimonySubscriptionDataFactory;
        private readonly IToastNotification toastNotification;
        public SubscriptionsController(ISubscriptionDataFactory subscriptionDataFactory,IToastNotification toast,
            IMatrimonySubscriptionDataFactory matrimonySubscriptionData)
        {
            _subscriptionDataFactory = subscriptionDataFactory;
            toastNotification = toast;
            matrimonySubscriptionDataFactory = matrimonySubscriptionData;
        }
        public IActionResult MatrimonySubscriptionCharges()
        {

            List<SBMSubscriptionCharges> subscriptions = matrimonySubscriptionDataFactory.Getsubscriptioncharges();
            List<SubscriptionViewModel> subscriptionsViewModel = new List<SubscriptionViewModel>();
            foreach (var item in subscriptions)
            {
                SubscriptionViewModel viewModel = new SubscriptionViewModel()
                {
                    Id = item.Id,
                    Charges = item.SubscriptionCharges
                };
                subscriptionsViewModel.Add(viewModel);
            }
            SubscriptionViewModel model = new SubscriptionViewModel()
            {
                SubCharges = subscriptionsViewModel
            };


            return View(model);

        }

        public IActionResult MemberPortalSubscriptionCharges()
        {
            List<SBMSubscriptionCharges> subscriptions = _subscriptionDataFactory.Getsubscriptioncharges();
            List<SubscriptionViewModel> subscriptionsViewModel = new List<SubscriptionViewModel>();
            foreach (var item in subscriptions)
            {
                SubscriptionViewModel viewModel = new SubscriptionViewModel()
                {
                    Id = item.Id,
                    Charges = item.SubscriptionCharges
                };
                subscriptionsViewModel.Add(viewModel);
            }
            SubscriptionViewModel model = new SubscriptionViewModel()
            {
                SubCharges = subscriptionsViewModel
            };


            return View(model);
        }

        public IActionResult EditMembersubscription(int id)
        {
            var sub = _subscriptionDataFactory.Getsubscriptioncharges().Where(x => x.Id == id).FirstOrDefault();
            SubscriptionViewModel subscriptionViewModel = new SubscriptionViewModel()
            {
                Id = sub.Id,
                Charges = sub.SubscriptionCharges
            };
            return View(subscriptionViewModel);
        }

        [HttpPost]
        public IActionResult EditMembersubscription(SubscriptionViewModel viewModel)
        {
            if(viewModel!=null)
            {
                SBMSubscriptionCharges subscription = new SBMSubscriptionCharges()
                {
                    Id = viewModel.Id,
                    SubscriptionCharges = viewModel.Charges
                };
                ResponseDTO response=_subscriptionDataFactory.UpdateSubscriptionDetails(subscription);
                if(response!=null && response.Result=="Success")
                {
                    toastNotification.AddSuccessToastMessage(response.Message);
                }
                else
                {
                    toastNotification.AddErrorToastMessage(response.Message);
                }
            }
            return RedirectToAction("MemberPortalSubscriptionCharges");
        }
        public IActionResult EditMatrimonysubscription(int id)
        {
            var sub = matrimonySubscriptionDataFactory.Getsubscriptioncharges().Where(x => x.Id == id).FirstOrDefault();
            SubscriptionViewModel subscriptionViewModel = new SubscriptionViewModel()
            {
                Id = sub.Id,
                Charges = sub.SubscriptionCharges
            };
            return View(subscriptionViewModel);
        }

        [HttpPost]
        public IActionResult EditMatrimonysubscription(SubscriptionViewModel viewModel)
        {
            if (viewModel != null)
            {
                SBMSubscriptionCharges subscription = new SBMSubscriptionCharges()
                {
                    Id = viewModel.Id,
                    SubscriptionCharges = viewModel.Charges
                };
                ResponseDTO response = matrimonySubscriptionDataFactory.UpdateSubscriptionDetails(subscription);
                if (response != null && response.Result == "Success")
                {
                    toastNotification.AddSuccessToastMessage(response.Message);
                }
                else
                {
                    toastNotification.AddErrorToastMessage(response.Message);
                }
            }
            return RedirectToAction("MatrimonySubscriptionCharges");
        }
    }
}

SBMMember.Web/Views/Subscriptions/EditMatrimonysubscription.cshtml
@model SubscriptionViewModel
@{
    ViewData["Title"] = "EditMatrimonysubscription";
    Layout = "~/Views/Shared/_LayoutAdminDashboard.cshtml";
}



<section class="blog_area single-post-area section_padding">
    <div class="container">

        <div class="row">
            <div class="col-lg-12">
                <div class="scroll">
                    <p>Update Matrimony App Subscription charges</p>
                </div>
                <div>
                </div>
            </div>
        </div>



        <div class="section-top-border">
            <div class="row" id="BusinessForm">
                <div class="col-lg-12 col-md-12">
                    <form asp-action="EditMatrimonysubscription" asp-controller="subscriptions" method="post">
                        <div class="row">
                            <div class="col-lg-12">
                                <input type="hidden" asp-for="Id" />
                                <input type="text" name="Charges" asp-for="Charges" placeholder="subscription charges" onfocus="this.placeholder = ''" onblur="this.placeholder = 'subscription charges'"
                                       required class="single-input">
                            </div>
                        </div>



                        <div class="row">
                            <div class="col-lg-4">
                               
                            </div>
                            <div class="col-lg-4" style="margin-top:10px">
                                <input type="submit" class="genric-btn primary-border" value="Submit" />
                                <a asp-action="MatrimonySubscriptionCharges" asp-controller="Subscriptions" id="btnCancel" class="genric-btn primary-border">Cancel</a>
                            </div>
                            <div class="col-lg-4">

                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


    

</section>

SBMMember.Web/Views/Subscriptions/EditMembersubscription.cshtml
@model SubscriptionViewModel
@{
    ViewData["Title"] = "EditMembersubscription";
    Layout = "~/Views/Shared/_LayoutAdminDashboard.cshtml";
}

<section class="blog_area single-post-area section_padding">
    <div class="container">

        <div class="row">
            <div class="col-lg-12">
                <div class="scroll">
                    <p>Update Member Portal Subscription charges</p>
                </div>
                <div>
                </div>
            </div>
        </div>



        <div class="section-top-border">
            <div class="row" id="BusinessForm">
                <div class="col-lg-12 col-md-12">
                    <form asp-action="EditMembersubscription" asp-controller="subscriptions" method="post">
                        <div class="row">
                            <div class="col-lg-12">
                                <input type="hidden" asp-for="Id" />
                                <input type="text" name="Charges" asp-for="Charges" placeholder="subscription charges" onfocus="this.placeholder = ''" onblur="this.placeholder = 'subscription charges'"
                                       required class="single-input">
                            </div>
                        </div>



                        <div class="row">
                            <div class="col-lg-4">
                               
                            </div>
                            <div class="col-lg-4" style="margin-top:10px">
                                <input type="submit" class="genric-btn primary-border" value="Submit" />
                                <a asp-action="MemberPortalSubscriptionCharges" asp-controller="Subscriptions" id="btnCancel" class="genric-btn primary-border">Cancel</a>
                            </div>
                            <div class="col-lg-4">

                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


    

</section>

SBMMember.Web/Views/Subscriptions/MatrimonySubscriptionCharges.cshtml
@model SubscriptionViewModel
@{
    ViewData["Title"] = "MatrimonySubscriptionCharges";
    Layout = "~/Views/Shared/_LayoutAdminDashboard.cshtml";
}


<script>
    $(document).ready(function () {
       
        $('#tblJobPost').DataTable();
       
    });
</script>

<section class="blog_area single-post-area section_padding">
    <div class="container">

        <div class="row">
            <div class="col-lg-12">
                <div class="scroll">
                    <p>Matrimony App Subscription charges</p>
                </div>
                <div>
                </div>
            </div>
        </div>



       
    </div>


    <div class="container">
       @* <div class="col-lg-12">
            <button value="Add New" id="btnAddNew" class="btn btn-danger">Add New</button>
        </div>
        <br />*@
        <div class="row">
            <div class="col-lg-12">
                <table id="tblJobPost" class="display" style="width:100%">
                    <thead>
                        <tr>
                            
                            <th>Matrimony App Subscription charges</th>
                            
                            <th>Operations</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.SubCharges != null)
                        {
                            foreach (var marquee in Model.SubCharges)
                            {
                                <tr>
                                    <td>@marquee.Charges</td>
                                   
                                   

                                    <td>
                                        <a title="Edit" href="@Url.Action("EditMatrimonysubscription","Subscriptions",new { id = marquee.Id})"><i class="ti-pencil"></i></a>
                                        
                                    </td>
                                </tr>
                            }

                        }
                    </tbody>

                </table>
            </div>
        </div>
    </div>

</section>

SBMMember.Web/Views/Subscriptions/MemberPortalSubscriptionCharges.cshtml
@model SubscriptionViewModel
@{
    ViewData["Title"] = "MemberPortalSubscriptionCharges";
    Layout = "~/Views/Shared/_LayoutAdminDashboard.cshtml";
}

<script>
    $(document).ready(function () {
       
        $('#tblJobPost').DataTable();
       
    });
</script>

<section class="blog_area single-post-area section_padding">
    <div class="container">

        <div class="row">
            <div class="col-lg-12">
                <div class="scroll">
                    <p>Member Portal Subscription charges</p>
                </div>
                <div>
                </div>
            </div>
        </div>



       
    </div>


    <div class="container">
       @* <div class="col-lg-12">
            <button value="Add New" id="btnAddNew" class="btn btn-danger">Add New</button>
        </div>
        <br />*@
        <div class="row">
            <div class="col-lg-12">
                <table id="tblJobPost" class="display" style="width:100%">
                    <thead>
                        <tr>
                            
                            <th>Member Portal Subscription charges</th>
                            
                            <th>Operations</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.SubCharges != null)
                        {
                            foreach (var marquee in Model.SubCharges)
                            {
                                <tr>
                                    <td>@marquee.Charges</td>
                                   
                                   

                                    <td>
                                        <a title="Edit" href="@Url.Action("EditMembersubscription","Subscriptions",new { id = marquee.Id})"><i class="ti-pencil"></i></a>
                                        
                                    </td>
                                </tr>
                            }

                        }
                    </tbody>

                </table>
            </div>
        </div>
    </div>

</section>