SBMMember.Web/Models/EventTitlesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SBMMember.Models;
namespace SBMMember.Web.Models
{
    public class EventTitlesViewModel
    {
        public int Id { get; set; }
        public string EventTitle { get; set; }
        public string EventTitleM { get; set; }
        public List< EventTitles> EventTitles { get; set; }
    }
}

SBMMember.Web/Models/MemberMeetingsViewModel.cs
using SBMMember.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SBMMember.Web.Models
{
    public class MemberMeetingsViewModel
    {
        public int Id { get; set; }
        public string MeetingTitle { get; set; }
        public string MeetingURL { get; set; }
        public DateTime MeetingDate { get; set; }
        public string Status { get; set; }
        public List<MemberMeetings> MemberMeetings { get; set; }
    }
}

SBMMember.Web/Controllers/AdminDashboardController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SBMMember.Web.Models;
using SBMMember.Models;
using SBMMember.Data.DataFactory;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using SBMMember.Web.Helper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using NToastNotify;
//using AspNetCoreHero.ToastNotification.Abstractions;

namespace SBMMember.Web.Controllers
{
    //[Authorize]
    public class AdminDashboardController : Controller
    {
        private readonly IMemberBusinessDataFactory businessDataFactory;
        private readonly IJobPostingDataFactory jobPostingDataFactory;
        private readonly IEventDataFactory eventDataFactory;
        private readonly IEventAdsDataFactory eventAdsDataFactory;
        private readonly IMapper mapper;
        private IWebHostEnvironment Environment;
        private readonly IUpcomingEventsDataFactory upcomingEventsDataFactory;
        private readonly IEventTitlesDataFactory eventTitlesDataFactory;
        // private readonly INotyfService _notyf;
        private readonly IToastNotification _toastNotification;
        private readonly IMemberMeetingsDataFactory meetingsDataFactory;
        public AdminDashboardController(IMemberBusinessDataFactory dataFactory, IMapper _mapper, IJobPostingDataFactory _jobPostingDataFactory, IEventDataFactory _eventDataFactory, IWebHostEnvironment hostEnvironment,
            IEventAdsDataFactory adsDataFactory, IUpcomingEventsDataFactory _upcomingEventsDataFactory, IEventTitlesDataFactory _eventTitlesDataFactory,
            IToastNotification toast, IMemberMeetingsDataFactory memberMeetings)
        {
            businessDataFactory = dataFactory;
            mapper = _mapper;
            jobPostingDataFactory = _jobPostingDataFactory;
            eventDataFactory = _eventDataFactory;
            Environment = hostEnvironment;
            eventAdsDataFactory = adsDataFactory;
            upcomingEventsDataFactory = _upcomingEventsDataFactory;
            eventTitlesDataFactory = _eventTitlesDataFactory;
            _toastNotification = toast;
            meetingsDataFactory = memberMeetings;
            //_notyf = notyf;
        }
        public IActionResult AdminHome()
        {
            return View();
        }

        public IActionResult JobPost()
        {
            List<JobPostings> jobPostings = jobPostingDataFactory.GetJobPostings();
            List<JobPostingViewModel> jobs = new List<JobPostingViewModel>();
            foreach (JobPostings job in jobPostings)
            {
                JobPostingViewModel model = mapper.Map<JobPostingViewModel>(job);
                jobs.Add(model);
            }
            JobPostingViewModel postingViewModel = new JobPostingViewModel()
            {
                JobPostings = jobs
            };
            return View(postingViewModel);

        }
        public IActionResult DeleteJobPosting(int Id)
        {

            ResponseDTO response = jobPostingDataFactory.DeleteJobDetails(Id);
            if (response.Result == "Success")
            {
                _toastNotification.AddSuccessToastMessage(response.Message);
            }
            else
                _toastNotification.AddErrorToastMessage(response.Message);
            return RedirectToAction("JobPost");
        }
        public IActionResult JobEdit(int Id)
        {
            JobPostings job = jobPostingDataFactory.GetJobDetails(Id);
            JobPostingViewModel model = mapper.Map<JobPostingViewModel>(job);
            ViewBag.EditMode = "Yes";
            // _notyf.Success($"{job.JobTitle} updated successfully.");

            return View("JobEdit", model);
        }
        [HttpPost]
        public IActionResult JobEdit(JobPostingViewModel model)
        {
            JobPostings job = mapper.Map<JobPostings>(model);
            jobPostingDataFactory.UpdateJobDetails(job);

            ModelState.Clear();
            // Alert($"{job.JobTitle} updated successfully.", Enum.NotificationType.success);
            _toastNotification.AddSuccessToastMessage($"{job.JobTitle} updated successfully.");
            return RedirectToAction("JobPost");
        }
        [HttpPost]
        public IActionResult JobPost(JobPostingViewModel model)
        {
            JobPostings job = mapper.Map<JobPostings>(model);
            ResponseDTO response = jobPostingDataFactory.AddJobDetails(job);
            if (response.Result == "Success")
            {
                _toastNotification.AddSuccessToastMessage(response.Message);
            }
            else
                _toastNotification.AddErrorToastMessage(response.Message);

            ModelState.Clear();
            List<JobPostings> jobPostings = jobPostingDataFactory.GetJobPostings();
            List<JobPostingViewModel> jobs = new List<JobPostingViewModel>();
            foreach (JobPostings _job in jobPostings)
            {
                JobPostingViewModel _model = mapper.Map<JobPostingViewModel>(_job);
                jobs.Add(_model);
            }
            JobPostingViewModel postingViewModel = new JobPostingViewModel()
            {
                JobPostings = jobs
            };
            return View(postingViewModel);
        }

        public IActionResult AddBusiness()
        {

            List<Member_BusinessDetails> buisnessList = businessDataFactory.GetAllBusinessDetails();
            List<MemberBusinessViewModel> businesses = new List<MemberBusinessViewModel>();
            foreach (Member_BusinessDetails item in buisnessList)
            {
                MemberBusinessViewModel model = mapper.Map<MemberBusinessViewModel>(item);
                businesses.Add(model);
            }
            MemberBusinessViewModel businessViewModel = new MemberBusinessViewModel()
            {
                MemberBusinesses = businesses
            };
            return View(businessViewModel);
        }
        [HttpPost]
        public IActionResult AddBusiness(MemberBusinessViewModel model)
        {
            Member_BusinessDetails member_Business = mapper.Map<Member_BusinessDetails>(model);
            var memberId = User.Claims?.FirstOrDefault(x => x.Type.Equals("MemberId", StringComparison.OrdinalIgnoreCase))?.Value;
            int MemberId = Convert.ToInt32(memberId);
            member_Business.MemberId = MemberId;
            ResponseDTO response = businessDataFactory.AddDetails(member_Business);
            if (response.Result == "Success")
                _toastNotification.AddSuccessToastMessage(response.Message);
            else
                _toastNotification.AddErrorToastMessage(response.Message);

            //return View();
            List<Member_BusinessDetails> buisnessList = businessDataFactory.GetAllBusinessDetails();
            List<MemberBusinessViewModel> businesses = new List<MemberBusinessViewModel>();
            foreach (Member_BusinessDetails item in buisnessList)
            {
                MemberBusinessViewModel models = mapper.Map<MemberBusinessViewModel>(item);
                businesses.Add(models);
            }
            MemberBusinessViewModel businessViewModel = new MemberBusinessViewModel()
            {
                MemberBusinesses = businesses
            };
            return View(businessViewModel);
        }
        public IActionResult DeleteBusiness(int Id)
        {
            ResponseDTO response = businessDataFactory.DeleteDetailsById(Id);
            if (response.Result == "Success")
                _toastNotification.AddSuccessToastMessage(response.Message);
            else
                _toastNotification.AddErrorToastMessage(response.Message);
            return RedirectToAction("AddBusiness");
        }
        public IActionResult EditBusiness(int Id)
        {
            Member_BusinessDetails businessDetails = businessDataFactory.GetDetailsById(Id);

            MemberBusinessViewModel models = mapper.Map<MemberBusinessViewModel>(businessDetails);
            return View(models);
        }
        [HttpPost]
        public IActionResult EditBusiness(MemberBusinessViewModel model)
        {
            Member_BusinessDetails member_Business = mapper.Map<Member_BusinessDetails>(model);
            ResponseDTO response = businessDataFactory.UpdateDetails(member_Business);

            if (response.Result == "Success")
                _toastNotification.AddSuccessToastMessage(response.Message);
            else
                _toastNotification.AddErrorToastMessage(response.Message);
            return RedirectToAction("AddBusiness");
        }
        public IActionResult AddEvent()
        {
            EventViewModel viewModel = new EventViewModel()
            {
                EventInfos = eventDataFactory.GetAllEventList(),
                EventTitles = eventTitlesDataFactory.GetEventTitles().Select(x => new SelectListItem() { Value = x.EventTitle, Text = x.EventTitle }).ToList(),
                EventYears = YearHelper.GetYears()
            };
            //viewModel.EventNameM = TranslationHelper.Translate("Samata Bhratru");
            viewModel.EventTitles.Insert(0, new SelectListItem() { Text = " Select Event Title ", Value = "0" });
            return View(viewModel);
        }
        [HttpPost]
        public IActionResult AddEvent(EventViewModel model)
        {
            EventInfo eventInfo = new EventInfo()
            {
                EventName = model.EventName,
                EventDescription = model.EventDescription,
                EventYear = model.EventYear,
                Status = "Active",
                CreateDate = DateTime.Now

            };
            EventInfo info = eventDataFactory.AddEventInfo(eventInfo);
            string path = Path.Combine(this.Environment.WebRootPath, "EventGallery");
            if (!Directory.Exists(path))

SBMMember.Web/Controllers/BannerController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SBMMember.Web.Models;
using SBMMember.Web.Helper;
using Microsoft.AspNetCore.Authorization;
using System.IO;
using SBMMember.Models;
using NToastNotify;
using SBMMember.Data.DataFactory;
using Microsoft.AspNetCore.Hosting;

namespace SBMMember.Web.Controllers
{
    [Authorize]
    public class BannerController : Controller
    {
        private readonly IToastNotification toastNotification;
        private readonly IBannerAdsDataFactory bannerAdsDataFactory;
        private IWebHostEnvironment Environment;
        public BannerController(IToastNotification toast, IBannerAdsDataFactory factory, IWebHostEnvironment hostEnvironment)
        {
            toastNotification = toast;
            bannerAdsDataFactory = factory;
            Environment = hostEnvironment;
        }
        public IActionResult ManageBanners()
        {
            BannerViewModel viewModel = new BannerViewModel()
            {
                Banners = BannerHelper.GetBanners()
            };
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult UploadBanner(BannerViewModel bannerViewModel)
        {
            Stream fs = bannerViewModel.BannerFile.OpenReadStream();
            BinaryReader br = new BinaryReader(fs);
            byte[] bytes = br.ReadBytes((Int32)fs.Length);

            ResponseDTO responsedto = BannerHelper.UploadBanner(bytes, bannerViewModel.Heading, bannerViewModel.BannerFile.FileName);
            if (responsedto.Result == "Success")
            {
                toastNotification.AddSuccessToastMessage(responsedto.Message);
            }
            else
                toastNotification.AddErrorToastMessage(responsedto.Message);
            return RedirectToAction("ManageBanners");
        }
        public IActionResult ViewBanner()
        {
            return RedirectToAction("ManageBanners");
        }

        public IActionResult DeletBanner(int id)
        {
            ResponseDTO responsedto = BannerHelper.RemoveBanner(id);
            if (responsedto.Result == "Success")
            {
                toastNotification.AddSuccessToastMessage(responsedto.Message);
            }
            else
                toastNotification.AddErrorToastMessage(responsedto.Message);
            return RedirectToAction("ManageBanners");
        }

        //Member Portal Banner adds started
        public IActionResult BannerAds()
        {
            BannerViewModel viewModel = new BannerViewModel()
            {
                bannerAds = bannerAdsDataFactory.GetBannerAds()
            };
            return View(viewModel);
        }
        [HttpPost]
        public IActionResult AddBanner(BannerViewModel viewModel)
        {
            string path = Path.Combine(this.Environment.WebRootPath, "Banners");
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }
            string fileName = Path.GetFileName(viewModel.BannerFile.FileName);
            string fullPath = Path.Combine(path, fileName);
            using (FileStream stream = new FileStream(fullPath, FileMode.Create))
            {
                viewModel.BannerFile.CopyTo(stream);

            }

            BannerAds banner = new BannerAds()
            {
                Heading = viewModel.Heading,
                ImageURL = $"~/Banners/{viewModel.BannerFile.FileName}",
            };

            ResponseDTO response = bannerAdsDataFactory.AddBannerAdsDetails(banner);
            if (response.Result == "Success")
            {
                toastNotification.AddSuccessToastMessage(response.Message);
            }
            else
                toastNotification.AddErrorToastMessage(response.Message);


            return RedirectToAction("BannerAds");
        }

        public IActionResult EditBanneradvt(int id)
        {
            BannerAds banner = bannerAdsDataFactory.GetBanerAdsById(id);
            BannerViewModel viewModel = new BannerViewModel();
            viewModel.Id = banner.Id;
            viewModel.Heading = banner.Heading;
            viewModel.ImageURL = banner.ImageURL;
            return View(viewModel);
        }
        [HttpPost]
        public IActionResult EditBanneradvt(BannerViewModel model)
        {
            BannerAds banner = new BannerAds();
            if (model.BannerFile != null)
            {
                string path = Path.Combine(this.Environment.WebRootPath, "Banners");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }
                string fileName = Path.GetFileName(model.BannerFile.FileName);
                string fullPath = Path.Combine(path, fileName);
                using (FileStream stream = new FileStream(fullPath, FileMode.Create))
                {
                    model.BannerFile.CopyTo(stream);

                }

                banner.Id= model.Id;
                banner.Heading = model.Heading;
                banner.ImageURL = $"~/Banners/{model.BannerFile.FileName}";

            }
            else
            {
                banner.Id = model.Id;
                banner.Heading = model.Heading;
                banner.ImageURL = model.ImageURL;
            }
            ResponseDTO response = bannerAdsDataFactory.UpdateBannerAdsDetails(banner);
            if (response.Result == "Success")
            {
                toastNotification.AddSuccessToastMessage(response.Message);
            }
            else
                toastNotification.AddErrorToastMessage(response.Message);
            return RedirectToAction("BannerAds");
        }
        public IActionResult DeletBannerAdvt(int id)
        {
            ResponseDTO response = bannerAdsDataFactory.DeleteBannerAdsDetails(id);
            if (response.Result == "Success")
            {
                toastNotification.AddSuccessToastMessage(response.Message);
            }
            else
                toastNotification.AddErrorToastMessage(response.Message);

            return RedirectToAction("BannerAds");
        }
    }
}

SBMMember.Web/Views/AdminDashboard/AddEvent.cshtml
@model EventViewModel
@{
    ViewData["Title"] = "AddEvent";
    Layout = "~/Views/Shared/_LayoutAdminDashboard.cshtml";
}

}
<script src="https://cdn.ckeditor.com/4.4.3/standard/ckeditor.js"></script>
<script>
    $(document).ready(function () {
        $("#eventForm").hide();
        $('#tblEvents').DataTable();
        $("#btnAddNew").click(function () {
            $("#eventForm").show();
            $(this).hide();
        });
        $("#btnCancel").click(function () {
            $("#eventForm").hide();
            $("#btnAddNew").show();
        });
    });
</script>
<section class="blog_area single-post-area section_padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 posts-list">
                <div class="col-lg-12">
                    <div class="scroll">
                        <p>Event Details</p>
                    </div>
                    <div>
                    </div>
                </div>


                <div class="section-top-border">
                    <div class="row" id="eventForm">
                        <div class="col-lg-10 col-md-10">
                            <form asp-action="AddEvent" asp-controller="AdminDashboard" method="post" enctype="multipart/form-data">

                                <div class="input-group-icon mt-10">
                                    <div class="form-select" id="default-select">
                                        <select asp-items="Model.EventYears" asp-for="EventYear">
                                           
                                        </select>
                                    </div>
                                </div>


                                <div class="input-group-icon mt-10">
                                    <div class="form-select" id="default-select">
                                        <select asp-for="EventName" asp-items="Model.EventTitles">
                                         
                                        </select>
                                    </div>
                                </div>
                                <div class="mt-10">
                                    <textarea class="single-textarea" id="text" name="EventDescription" asp-for="EventDescription" placeholder="EventDescription" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Event Description'"
                                              required></textarea>
                                </div>
                                <div class="mt-10">
                                    <p>upload event images</p>
                                    <input type="file" class="single-input" asp-for="FormFiles" multiple="multiple" placeholder="Event Description" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Event Descriptionn'" />
                                </div>
                                <div class="mt-10" style="float:right">
                                    <input type="submit" class="genric-btn primary" style="background-color:#77002e;margin-right:20px">
                                    <input type="button" id="btnCancel" class="genric-btn primary" style="background-color:#77002e;margin-right:20px" value="Cancel">
                                </div>
                            </form>
                        </div>

                    </div>
                </div>






            </div>

        </div>
    </div>
    @*Event list*@
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <button value="Add New" id="btnAddNew" class="btn btn-danger">Add New</button>
            </div>
            <br />
            <div class="col-lg-12">
                
                <table id="tblEvents" class="display" style="width:100%">
                    <thead>
                        <tr>
                            <th>Event Title</th>
                            <th>Event Description</th>
                            <th>Event Year</th>
                            <th>Operations</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.EventInfos != null)
                        {
                            foreach (var eventAd in Model.EventInfos)
                            {
                        <tr>
                            <td>@eventAd.EventName</td>
                            <td>@Html.Raw(string.Join(" ", eventAd.EventDescription.Split().Take(20)))</td>
                            <td>@eventAd.EventYear</td>
                           
                            <td>
                                <a href="@Url.Action("EditEvent","AdminDashboard",new { id = eventAd.EventId})"><i class="ti-pencil"></i></a>
                                <a title="Delete Event" href="@Url.Action("DeleteEvent","AdminDashboard",new { id = eventAd.EventId})" class="delete-row" onclick="return confirm('Are sure wants to delete?');"><i class="ti-close"></i></a>
                            </td>
                            
                        </tr>
                            }

                        }
                    </tbody>

                </table>
            </div>
        </div>
    </div>
</section>

<script>
        $(function () {
            CKEDITOR.replace('text');
        });
    </script>

SBMMember.Web/Views/AdminDashboard/AdminHome.cshtml
@{
    ViewData["Title"] = "AdminHome";
    Layout = "~/Views/Shared/_LayoutAdminDashboard.cshtml";
}


<!----------------------end of scroll bar---------------->
<div class="seperate"></div>

<!--------------dashboard-------------->
<div class="container ">
    <div class="row">
        <div class="col-lg-12" style="text-align:center">
            <!------------icon dashbaord row-1--------------->
            <div class="container">
                <div class="row ">
                    <div class="col-xs-4 r1c1 dashboard">
                        <a asp-action="ManageMembers" asp-controller="AdminDashboard">
                            <img src="~/img/team.png" class="dashboard-icon">
                            <h3 style="color:#000000">Manage Members</h3>
                        </a>
                    </div>
                    <div class="col-xs-4 r1c1 dashboard">
                        <a asp-action="JobPost" asp-controller="AdminDashboard">
                            <img src="~/img/jobs.png" class="dashboard-icon">
                            <h3 style="color:#000000">Manage Jobs</h3>
                        </a>
                    </div>
                    <div class="col-xs-4 r1c1 dashboard">
                        <a asp-action="ManageEvents" asp-controller="AdminDashboard">
                            <img src="~/img/add-event.png" class="dashboard-icon">
                            <h3 style="color:#000000">Manage Events</h3>
                        </a>
                    </div>

                </div>
            </div>
            <!------------End of icon dashbaord row-1--------------->
        </div>
    </div>
</div>
<div class="seperate"><hr style="border:1px dashed #a7a7a7"></div>

<div class="container ">
    <div class="row">
        <div class="col-lg-12" style="text-align:center">
            <!------------icon dashbaord row-2--------------->
            <div class="container">
                <div class="row ">
                    <div class="col-xs-4 r1c1 dashboard">
                        <a asp-action="AddBusiness" asp-controller="AdminDashboard">
                            <img src="~/img/add-video.png" class="dashboard-icon">
                            <h3 style="color:#000000">Manage Businesses</h3>
                        </a>
                    </div>
                    <div class="col-xs-4 r1c1 dashboard">
                        <a asp-action="AddEventAds" asp-controller="AdminDashboard">
                            <img src="~/img/add.png" class="dashboard-icon">
                            <h3 style="color:#000000">Manage Advertisements</h3>
                        </a>
                    </div>
                    <div class="col-xs-4 r1c1 dashboard">
                        @*<a asp-action="ManageBanners" asp-controller="Banner">*@
                            <a asp-action="ManageBannerAds" asp-controller="AdminDashboard">
                            <img src="~/img/scrolingads.png" class="dashboard-icon">
                            <h3 style="color:#000000">Manage Scrolling Ads</h3>
                        </a>
                    </div>
                   

                </div>
            </div>
            <!------------End of icon dashbaord row-2--------------->
        </div>
    </div>
</div>

<div class="seperate"><hr style="border:1px dashed #a7a7a7"></div>

<div class="container ">
    <div class="row">
        <div class="col-lg-12" style="text-align:center">
            <!------------icon dashbaord row-2--------------->
            <div class="container">
                <div class="row ">
                    <div class="col-xs-4 r1c1 dashboard">
                        <a asp-action="ManageAdminUsers" asp-controller="AdminUsers">
                            <img src="~/img/super-user.png" class="dashboard-icon">
                            <h3 style="color:#000000">Manage Super Users</h3>
                        </a>
                    </div>
                    <div class="col-xs-4 r1c1 dashboard">
                        <a asp-action="ManaageMarquees" asp-controller="Marquee">
                            <img src="~/img/marqueetext.png" class="dashboard-icon">
                            <h3 style="color:#000000">Manage Marquee Text</h3>
                        </a>
                    </div>
                    <div class="col-xs-4 r1c1 dashboard">
                        <a asp-action="MemberMeetings" asp-controller="AdminDashboard">
                            <img src="~/img/m-meeting.png" class="dashboard-icon">
                            <h3 style="color:#000000">Manage Meetings</h3>
                        </a>
                    </div>

                </div>
            </div>
            <!------------End of icon dashbaord row-2--------------->
        </div>
    </div>
</div>

<div class="seperate"><hr style="border:1px dashed #a7a7a7"></div>

<div class="container ">
    <div class="row">
        <div class="col-lg-12" style="text-align:center">
            <!------------icon dashbaord row-2--------------->
            <div class="container">
                <div class="row ">
                    <div class="col-xs-4 r1c1 dashboard">
                        <a asp-action="ManageSubscriptions" asp-controller="AdminDashboard">
                            <img src="~/img/subscribe.png" class="dashboard-icon">
                            <h3 style="color:#000000">Manage Subscription charges</h3>
                        </a>
                    </div>
                    <div class="col-xs-4 r1c1 dashboard">
                        @*<a asp-action="ManaageMarquees" asp-controller="Marquee">
                            <img src="~/img/marqueetext.png" class="dashboard-icon">
                            <h3 style="color:#000000">Manage Marquee Text</h3>
                        </a>*@
                    </div>
                    <div class="col-xs-4 r1c1 dashboard">
                        @*<a asp-action="MemberMeetings" asp-controller="AdminDashboard">
                            <img src="~/img/m-meeting.png" class="dashboard-icon">
                            <h3 style="color:#000000">Manage Meetings</h3>
                        </a>*@
                    </div>

                </div>
            </div>
            <!------------End of icon dashbaord row-2--------------->
        </div>
    </div>
</div>

SBMMember.Web/Views/AdminDashboard/ManageBannerAds.cshtml
@{
    ViewData["Title"] = "ManageBannerAds";
    Layout = "~/Views/Shared/_LayoutAdminDashboard.cshtml";
}


<div class="container ">
    <div class="row">
        <div class="col-lg-12" style="text-align:center">
            <!------------icon dashbaord row-1--------------->
            <div class="container">
                <div class="row ">
                    <div class="col-xs-4 r1c1 dashboard">
                        <a asp-action="ManageBanners" asp-controller="Banner">
                            <img src="~/img/matrimony-ads.png" class="dashboard-icon">
                            <h3 style="color:#000000">Matrimony App BannerAds Details</h3>
                        </a>
                    </div>
                    <div class="col-xs-4 r1c1 dashboard">
                        <a asp-action="BannerAds" asp-controller="Banner">
                            <img src="~/img/App Ads.png" class="dashboard-icon">
                            <h3 style="color:#000000">Member Portal BannerAds Details</h3>
                        </a>
                    </div>
                    <div class="col-xs-4 r1c1 dashboard">
                       @* <a asp-action="EventTitles" asp-controller="AdminDashboard">
                            <img src="~/img/e-title.png" class="dashboard-icon">
                            <h3 style="color:#000000">Add Event Titles</h3>
                        </a>*@
                    </div>

                </div>
            </div>
            <!------------End of icon dashbaord row-1--------------->
        </div>
    </div>
</div>
<div class="seperate"><hr style="border:1px dashed #a7a7a7"></div>